# Generated by Django 5.1.2 on 2024-10-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competencias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="penalizacion",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="puntuacion_art",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="puntuacion_da",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="puntuacion_db",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="puntuacion_e",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="puntuacion_ml",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
