# Generated by Django 5.1.2 on 2024-11-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competencias", "0002_alter_competencia_penalizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competencia",
            name="aparato",
            field=models.CharField(
                choices=[
                    ("Manos Libres", "Manos Libres"),
                    ("Aro", "Aro"),
                    ("Pelota", "Pelota"),
                    ("Cuerda", "Cuerda"),
                    ("Cinta", "Cinta"),
                    ("Masas", "Masas"),
                ],
                default="Manos Libres",
                max_length=20,
            ),
        ),
    ]
