# Generated by Django 5.1.2 on 2024-11-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competencias", "0003_competencia_aparato"),
    ]

    operations = [
        migrations.AddField(
            model_name="competencia",
            name="nombre_competencia",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
